### ISSUE TITLE
How can I tell which part I parse I the reference (chapter verse) versus the words themselves?

### ISSUE THREAD

**Issue by timfong888** [boblail/pericope#6]
For example, I need to be able to parse the following string:

```
“A wise son makes a glad father, but a foolish man despises his mother.”
‭‭Proverbs‬ ‭15:20‬ ‭ESV‬‬
http://bible.com/59/pro.15.20.esv
```
I need to discard the link (I can do that with regex), but then know that sentence (which could be multiple sentences, or a partial sentence) are the words, and then Proverbs 15:20 has a book, chapter, verse, and then a translation.

It looks like the text parse makes these each elements in an array.  Unless I am reading the docs wrong....but was hoping something could tell me the reference and then the actual text.  Thanks!

**Comment by timfong888** [comment]
I tried the following:

```
string = "“A wise son makes a glad father, but a foolish man despises his mother.” ‭‭Proverbs‬ ‭15:20‬ ‭ESV‬‬ http://bible.com/59/pro.15.20.esv"
Pericope.parse(string)
[]
```

**Comment by boblail** [comment]
@timfong888, you're reading the docs right.

You have some unicode whitespace (or invisible) characters in that string that `/\s/` doesn't match:

Here's what I copied-and-pasted from your example:
```ruby
"Proverbs‬ ‭15:20‬ ‭ESV".bytes # => [80, 114, 111, 118, 101, 114, 98, 115, 226, 128, 172, 32, 226, 128, 173, 49, 53, 58, 50, 48, 226, 128, 172, 32, 226, 128, 173, 69, 83, 86]
```

Here's what I typed in the terminal:
```ruby
"Proverbs 15:20 ESV".bytes # => [80, 114, 111, 118, 101, 114, 98, 115, 32, 49, 53, 58, 50, 48, 32, 69, 83, 86]
```

In the first example, the bytes `[226, 128, 172, 32, 226, 128, 173]` lie between the `s` in `Proverbs` and the `1` in `15:20`. In the second example, only the byte `[32]` lies between them.

Maybe normalize your source text before passing it to `Pericope.parse`?

**Comment by timfong888** [comment]
Cool, thanks, I'll try that.  Perhaps these are html_entities?

On Tue, Jun 7, 2016 at 6:34 AM, Bob Lail <notifications@github.com> wrote:

> @timfong888 <https://github.com/timfong888>, you're reading the docs
> right.
>
> You have some unicode whitespace (or invisible) characters in that string
> that /\s/ doesn't match:
>
> Here's what I copied-and-pasted from your example:
>
> "Proverbs‬ ‭15:20‬ ‭ESV".bytes # => [80, 114, 111, 118, 101, 114, 98, 115, 226, 128, 172, 32, 226, 128, 173, 49, 53, 58, 50, 48, 226, 128, 172, 32, 226, 128, 173, 69, 83, 86]
>
> Here's what I typed in the terminal:
>
> "Proverbs 15:20 ESV".bytes # => [80, 114, 111, 118, 101, 114, 98, 115, 32, 49, 53, 58, 50, 48, 32, 69, 83, 86]
>
> In the first example, the bytes [226, 128, 172, 32, 226, 128, 173] lie
> between the s in Proverbs and the 1 in 15:20. In the second example, only
> the byte [32] lies between them.
>
> Maybe normalize your source text before passing it to Pericope.parse?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/boblail/pericope/issues/6#issuecomment-224281583>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAA254zqx0BE3PNulMAJLs49ePpFDf5Pks5qJXNmgaJpZM4Ivj35>
> .
>



-- 
-----------------------------------------------
Tim Fong
timfong888@gmail.com
415-508-6888

**Comment by timfong888** [comment]
Does `original_string` correct the input to be the proper book format, or is it literally, whatever I originally typed?

```
text = Pericope.split(@inbound_text)
=> ["The Sovereign Lord is my strength; he makes my feet like the feet of a deer, he enables me to tread on the heights. For the director of music. On my stringed instruments.\n",
 #<Pericope:0x0055f36f217b78
  @book=35,
  @book_chapter_count=3,
  @book_name="Habakkuk",
  @original_string="Habakkuk 3:19",
  @ranges=[35003019..35003019]>,
 " NIV"]
```

**Comment by boblail** [comment]
It's literally what you originally typed.

```ruby
=> Pericope.parse("ps 118")
=> [#<Pericope:0x007f9e1d976310 @original_string="ps 118", @book=19, @book_name="Psalm", @book_chapter_count=150, @ranges=[19118001..19118029]>]
```
