### ISSUE TITLE
Not able to parse passage without space

### ISSUE THREAD

**Issue by arn01d** [boblail/pericope#8]
Hi @boblail, I'm using your code successfully with a Twitter bot @arnoldfungai. However, I have noted that Pericope cannot parse a passage written like `Psalm1` or `Ps1`. It is requiring it be written `Psalm 1` or `Ps 1 `to parse successful. 

This can be a problem since some people may not put a space between book and chapter. 

Your code is greatly appreciated. Many thanks

**Comment by boblail** [comment]
Hi @arn01d, good call!

I just cut a new version of the gem (0.6.3) that matches pericopes when the space between book and reference is omitted.
