### ISSUE TITLE
Parsing problem

### ISSUE THREAD

**Issue by jaredjackson** [boblail/pericope#9]
There seems to be a parsing problem with 1 Cor. In my fork, I have added some tests that demonstrate the issue. When text precedes an abbreviated reference to 1 Corinthians (i.e. 1 Cor.) the pericope isn't picked up.

see https://github.com/jaredjackson/pericope/blob/master/test/additional_pericope_test.rb

**Comment by boblail** [comment]
Thanks @jaredjackson! That should be fixed now on master by #10
